sudo: required
dist: trusty
group: edge
language: clojure
lein: lein
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

matrix:
  allow_failures:
    - jdk: oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

cache:
  directories:
    - $HOME/.m2
env:
  global:
    - DATADOG_API_KEY=9775a026f1ca7d1c6c5af9d94d9595a4
    - HIPCHAT_SERVER=api.hipchat.com
    - HIPCHAT_API_KEY=2YotnFZFEjr1zCsicMWpAA
    - HIPCHAT_ALERT_ROOM="#fake"
    - LIBRATO_METRICS_USER="faker"
    - LIBRATO_METRICS_API_KEY="75AFDB82"
    - OPSGENIE_SERVICE_KEY="eb243592-faa2-4ba2-a551q-1afdf565c889"
    - OPSGENIE_RECIPIENTS=fakebob
    - SLACK_API_KEY="xoxp-113552566178-113639658309-193597780375-2a4e44931d4827e06f495cbca9d6e7b5"
    - SLACK_ALERT_ROOM="#fake"
    - SLACK_ALERT_ACCOUNT="@fakebob"
    - TELEGRAM_API_TOKEN="1233456789ABC"
    - TELEGRAM_CHAT_ID="1234"
