name: Build new artifacts

on:  
  push:
    tags:
      - '*.*.*'

  workflow_dispatch:

jobs:  
  build:
    runs-on: ubuntu-latest
    container: clojure:lein
    steps:
      - uses: actions/checkout@v2
      - name: install os deps
        run: |
          apt-get -qq update && apt-get -qy install rpm fakeroot
      - name: install lein deps
        run: |
          lein install
      - name: build packages
        run: |
          lein pkg
      - uses: actions/upload-artifact@v2
        with:
          name:  ${{ github.event.release.tag_name }}
          path: ./target/**
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.release.tag_name }}
        with:
          draft: true
          files: ./target/**

  clojars:
    runs-on: ubuntu-latest
    container: clojure:lein
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: jlesquembre/clojars-publish-action@0.3
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}   

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: | 
            riemann/riemann:latest
            riemann/riemann:${{ github.event.release.tag_name }}
